import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="fixed top-0 flex w-full flex-row gap-4 bg-gray-700 p-4 text-white underline">
          <Link href="/" replace>
            Home
          </Link>
          <Link href="/person" replace>
            Person
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
